version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto17
    commands:
      - echo Installing Maven-3.9.5...
      - cd ./frontend
      - npm install -g @angular/cli
      - npm install
      - curl -L -o apache-maven-3.9.5-bin.tar.gz https://dlcdn.apache.org/maven/maven-3/3.9.5/binaries/apache-maven-3.9.5-bin.tar.gz
      - tar xzf apache-maven-3.9.5-bin.tar.gz
      - export M2_HOME=$PWD/apache-maven-3.9.5
      - export M2=$PWD/apache-maven-3.9.5/bin
      - export PATH=$M2:$PATH
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - echo Checking Maven and Java Version...
      - java -version
      - mvn -version
      - echo AWS authentication
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com
  pre_build:
    commands:
      ## compile and build .jar files
      - echo Compile and build backend services..
      - cd ../service-discovery
      - mvn clean install -DskipTests
      - cd ../booking
      - mvn clean install -DskipTests
      - cd ../workspace
      - mvn clean install -DskipTests
      - echo Compile and build backend services completed..
  build:
    commands:
      #build frontend
      - echo Building docker images...
      - echo Building frontend...
      - cd ../frontend
      - docker build -t frontend .
      - docker tag frontend:latest 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:latest
      - docker push 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:latest
      - echo Frontend build completed...
      #build services
      - echo Building service discovery...
      - ls -l # list all contents in the directory
      - cd ../service-discovery
      - mvn package
      - docker build -t service-discovery -f Dockerfile .
      - docker tag service-discovery:latest 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/service-discovery:latest
      - docker push 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/service-discovery:latest
      - echo Building workspace service...
      - cd ../workspace
      - mvn package
      - docker build -t workspace -f Dockerfile .
      - docker tag workspace:latest 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/workspace:latest
      - docker push 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/workspace:latest
      - echo Building booking service...
      - cd ../booking
      - mvn package 
      - docker build -t booking -f Dockerfile .
      - docker tag booking:latest 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/booking:latest
      - docker push 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/booking:latest
      - echo Backend services build completed...
      - echo Docker images build completed...
      #- mvn package -f service-discovery/pom.xml
      #- mvn package -f workspace/pom.xml
      #- mvn package -f booking/pom.xml
  post_build:
    commands:
      - echo Pushing docker images...d
      # - docker push wbms-frontend:wbms-frontend-docker .
      - cd ..
      # - docker push 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/frontend:latest
      # - cd service-discovery
      # - docker push wbms-service-discovery-docker:service-discovery-docker ./docker
      - cd ./service-discovery
      # - docker push 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/service-discovery:latest
      - cd ../workspace
      # - docker push wbms-workspace-docker:workspace-docker ./docker
      # - docker push 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/workspace:latest
      - cd ../booking
      # - docker push wbms-booking-docker:booking-docker ./docker
      # - docker push 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/booking:latest
      - echo "Docker images push completed."

artifacts:
  files:
    - ./frontend/dist/**/*  # Angular frontend build artifacts
    - ./service-discovery/target/*.jar
    - ./workspace/target/*.jar
    - ./booking/target/*.jar
    - docker-compose.yml
  name: wbms-artifacts

#cache dependencies
cache:
  paths:
    - frontend/node_modules/**/*
    - service-discovery/.m2/repository/**/*
    - workspace/.m2/repository/**/*
    - booking/.m2/repository/**/*
