version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - cd angular-app
      - npm install
  build:
    commands:
      - npm run build
      - cd ..
      - mvn package -f service-discovery/pom.xml
      - mvn package -f workspace/pom.xml
      - mvn package -f booking/pom.xml
  post_build:
    commands:
      - echo "Build and deployment completed."S

artifacts:
  files: '**/*'