version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
      java: corretto17
    commands:
      - npm install -g @angular/cli
      - yum install -y maven
      - java -version
      - mvn -version 
  build:
    commands:
      #build frontend
      - npm install
      - ng build
    
      #build services
      - cd service-discovery
      - mvn clean install
      - cd ../booking
      - mvn clean install
      - cd ../workspace
      - mvn clean install


      - mvn package -f workspace/pom.xml
      - mvn package -f booking/pom.xml
  post_build:
    commands:
      - echo "Build and deployment completed."

artifacts:
  files:
    - ./dist/**/*  # Angular frontend build artifacts
    - ./service-discovery/target/*.jar  
    - ./workspace/target/*.jar 
    - ./booking/target/*.jar 
  name: wbms-artifacts

#cache dependencies
cache:
  paths:
    - node_modules/**/*  
    - service-discovery/.m2/repository/**/*  
    - workspace/.m2/repository/**/*  
    - booking/.m2/repository/**/*  
