version: "3"
services:
  service-discovery:
    container_name: service-discovery
    ports:
      - "80:8761"
    image: 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/service-discovery
  booking:
    container_name: booking
    depends_on:
      - service-discovery
    ports:
      - "80:8081"
    image: 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/booking
  workspace:
    container_name: workspace
    depends_on:
      - service-discovery
    ports:
      - "80:8082"
    image: 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/workspace
  frontend:
    container_name: frontend
    #depends_on:
    #  - service-discovery
    #  - booking
    #  - workspace
    ports:
      - "80:80"
    image: 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/frontend

