version: "3"
services:
  frontend:
    container_name: frontend
    depends_on:
      - service-discovery
      - booking
      - workspace
    ports:
      - "4200:4200"
    image: 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/frontend
  service-discovery:
    container_name: service-discovery
    ports:
      - "8761:8761"
    image: 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/service-discovery
  booking-service:
    container_name: booking
    depends_on:
      - service-discovery
    ports:
      - "8081:8081"
    image: 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/booking
  workspace-service:
    container_name: workspace
    depends_on:
      - service-discovery
    ports:
      - "8082:8082"
    image: 952359380490.dkr.ecr.ap-southeast-1.amazonaws.com/workspace

